import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar';
import { CartProvider } from './context/CartProvider';
import Footer from './components/Footer';
import ToastProvider from './components/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Busana90s',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <CartProvider>
          <Navbar />
          <ToastProvider>{children}</ToastProvider>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
