const PENDING_PAYMENT = 'PENDING_PAYMENT';
const PAID = 'PAID';
const CANCELED = 'CANCELED';
const SHIPPING = 'SHIPPING';
const FRONT_END_URL = process.env.FRONT_END_URL;
const MIDTRANS_SERVER_KEY = process.env.MIDTRANS_SERVER_KEY;
const MIDTRANS_APP_URL = process.env.MIDTRANS_APP_URL;
const MIDTRANS_API_URL = process.env.MIDTRANS_API_URL;

module.exports = {
  PENDING_PAYMENT,
  PAID,
  CANCELED,
  FRONT_END_URL,
  MIDTRANS_APP_URL,
  MIDTRANS_SERVER_KEY,
  MIDTRANS_API_URL,
  SHIPPING,
};
